name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
    - uses: actions/checkout@v2    
    - name: Build
    - run: make all    
    - name: Build tests
    - run: make tests     
    - name: Execute tests
    - run: ./bin/unittest
      
